import { pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { customers } from "./customers.js";

/**
 * basket_sessions table
 *
 * Stores basket sessions for both guest and authenticated customers (D-01).
 *
 * Key design decisions:
 * - customerId: nullable FK — null for guest sessions, non-null for authenticated (D-01).
 * - guestToken: unique UUID cookie value stored as httpOnly cookie `grovio_basket_token` (D-01).
 *   Generated by the API on first basket access; sent back as a Set-Cookie header.
 *   null for authenticated customer sessions (they are identified by JWT).
 * - expiresAt: 30-day TTL enforced at service layer (D-03).
 *   BullMQ BasketExpiryJob cleans up expired guest sessions periodically.
 *
 * Merge on login: POST /basket/merge reads the guest token cookie + auth JWT,
 * merges items into the account basket, and clears the guest token cookie (D-02).
 *
 * Covers CHK-01, CHK-02.
 */
export const basketSessions = pgTable("basket_sessions", {
  id: uuid("id").defaultRandom().primaryKey(),

  /**
   * FK to the authenticated customer who owns this basket.
   * null = guest basket (keyed by guestToken cookie instead).
   * Cascade delete: removing a customer hard-deletes their basket session.
   */
  customerId: uuid("customer_id").references(() => customers.id, {
    onDelete: "cascade",
  }),

  /**
   * Random UUID stored in the httpOnly cookie `grovio_basket_token` (D-01).
   * Used to identify guest basket sessions across requests.
   * null for authenticated customer sessions (JWT identifies them instead).
   * Unique: one guest token maps to exactly one basket session.
   */
  guestToken: text("guest_token").unique(),

  /**
   * Basket expiry timestamp (D-03). 30-day TTL from session creation.
   * After this timestamp, the session is considered expired and items are invisible.
   * BasketExpiryJob deletes rows where expiresAt < NOW() on a schedule.
   */
  expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),

  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

/** TypeScript type for inserting a new basket session row */
export type InsertBasketSession = typeof basketSessions.$inferInsert;

/** TypeScript type for selecting a basket session row */
export type SelectBasketSession = typeof basketSessions.$inferSelect;
