import {
  bigint,
  pgEnum,
  pgTable,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";
import { customerAddresses } from "./customer-addresses.js";
import { customers } from "./customers.js";

/**
 * orderStatusEnum — 6 lifecycle states for the order state machine (D-08).
 *
 * Constrains status at the Postgres level — invalid values are rejected by the DB
 * even if service-layer validation is bypassed.
 *
 * State machine transitions (Claude's discretion per CONTEXT.md):
 *   pending_payment → payment_received (webhook PAYMENT_CAPTURED)
 *   payment_received → processing (vendor action)
 *   processing → shipped (vendor action)
 *   shipped → delivered (vendor action or delivery confirmation)
 *   pending_payment → cancelled (expiry or explicit cancel)
 *   payment_received → cancelled (before processing)
 *
 * Values MUST exactly match OrderStatusSchema in packages/contracts/src/orders/types.ts.
 */
export const orderStatusEnum = pgEnum("order_status", [
  "pending_payment",
  "payment_received",
  "processing",
  "shipped",
  "delivered",
  "cancelled",
]);

/**
 * orders table
 *
 * The customer-facing order record (ORD-01). One order maps to one customer and
 * one delivery address, but spans multiple vendors via vendor_orders sub-table (ORD-02, D-08).
 *
 * Key design decisions:
 * - displayId: human-readable, unique order reference (e.g., ORD-20240601-A3F9).
 *   Generated by OrderService at placement; customers see this in confirmation/history (D-08).
 * - All monetary columns are BIGINT minor units — no FLOAT/DECIMAL anywhere (Pitfall 1).
 * - couponCode: stored at placement time from the coupons table (Pitfall 6 — store code not
 *   discount amount). Server re-validates and applies discount from coupons table at placement.
 * - paymentProvider: text nullable — 'stripe' or 'razorpay'. Set when payment is initiated.
 * - providerOrderId: provider-side order/intent ID (D-10, Pitfall 8). Used by webhook
 *   handlers to look up the internal order when provider sends webhook. Set at PaymentIntent
 *   creation time — before client-side confirmation — to handle the webhook race (Pitfall 8).
 *
 * Covers ORD-01, ORD-02, WAL-05 (walletAppliedMinor).
 */
export const orders = pgTable("orders", {
  id: uuid("id").defaultRandom().primaryKey(),

  /**
   * Customer-facing order display ID.
   * Format: ORD-YYYYMMDD-XXXX (Claude's discretion per CONTEXT.md).
   * Unique across all orders. Generated by OrderService using a short random suffix.
   */
  displayId: text("display_id").notNull().unique(),

  /**
   * FK to the customer who placed the order.
   * Non-null — orders require authentication (no guest checkout in Phase 5).
   */
  customerId: uuid("customer_id")
    .notNull()
    .references(() => customers.id),

  /**
   * FK to the delivery address selected at checkout.
   * nullable — set on the address step; may be null for digital goods in future phases.
   */
  addressId: uuid("address_id").references(() => customerAddresses.id),

  /**
   * Order lifecycle status (pgEnum — constrained at DB level).
   * Default 'pending_payment': new orders wait for webhook confirmation.
   * Transitions managed exclusively by OrderService named methods (never direct SET).
   */
  status: orderStatusEnum("status").notNull().default("pending_payment"),

  /**
   * Sum of all line item subtotals before delivery and discounts.
   * BIGINT minor units (Pitfall 1). Backend-authoritative (CHK-04).
   */
  subtotalMinor: bigint("subtotal_minor", { mode: "number" }).notNull(),

  /**
   * Delivery / shipping fee for the order.
   * BIGINT minor units. Default 0 (free shipping or Phase 5 simplified handling).
   */
  shippingMinor: bigint("shipping_minor", { mode: "number" })
    .notNull()
    .default(0),

  /**
   * Total discount applied (coupon, promotion, etc.).
   * BIGINT minor units. Default 0 (no discount applied).
   */
  discountMinor: bigint("discount_minor", { mode: "number" })
    .notNull()
    .default(0),

  /**
   * Wallet credit applied to this order (D-13, WAL-05).
   * BIGINT minor units. Default 0 (no wallet credit used).
   * Set by CheckoutService; bounded by min(wallet_balance, order_total).
   * The remaining card charge = grandTotalMinor - walletAppliedMinor.
   */
  walletAppliedMinor: bigint("wallet_applied_minor", { mode: "number" })
    .notNull()
    .default(0),

  /**
   * Final amount to be charged via payment provider.
   * grandTotalMinor = subtotalMinor + shippingMinor - discountMinor - walletAppliedMinor.
   * BIGINT minor units. Backend-computed — never trusts client-provided amount (CHK-04).
   */
  grandTotalMinor: bigint("grand_total_minor", { mode: "number" }).notNull(),

  /**
   * Coupon code applied at order placement (Pitfall 6).
   * null = no coupon applied. Stored for display/audit purposes only.
   * Discount value is always re-derived from the coupons table — not from this field.
   */
  couponCode: text("coupon_code"),

  /**
   * Payment provider used for this order ('stripe' or 'razorpay').
   * null until the customer selects a provider on the payment step.
   * Set by PaymentService.createPaymentOrder() before provider API call.
   */
  paymentProvider: text("payment_provider"),

  /**
   * Provider-side order/intent ID (D-10, Pitfall 8).
   * Stripe: PaymentIntent ID (pi_xxx). Razorpay: order ID (order_xxx).
   * Set at PaymentIntent/order creation time — before client-side confirmation.
   * Webhook handlers look up this field to find the internal order.
   * Prevents the race condition where webhook fires before order is linked (Pitfall 8).
   */
  providerOrderId: text("provider_order_id"),

  createdAt: timestamp("created_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .defaultNow()
    .notNull(),
});

/** TypeScript type for inserting a new order row */
export type InsertOrder = typeof orders.$inferInsert;

/** TypeScript type for selecting an order row */
export type SelectOrder = typeof orders.$inferSelect;
